#! /bin/bash -e

BINDIR=$(cd "$(dirname "$0")" && pwd -P)
me=$(basename "$0")

if [ $(id -u) -eq 0 ]; then
  echo >&2 "*** $me: running DSS under superuser account is not supported."
  exit 1
fi

export DIP_HOME=$(dirname "$BINDIR")
export DKU_LAMBDA_HOME="$DIP_HOME"

# Load basic environment
source "$BINDIR"/env-default.sh
if [ -z "$DKUINSTALLDIR" ]; then
  echo >&2 "FATAL: DKUINSTALLDIR is not defined. Please check $BINDIR/env-default.sh"
  exit 1
fi
source "$DKUINSTALLDIR/scripts/_startup.inc.sh"

bkdl_set_py_env
bkdl_load_env_files
bkdl_env_sanity_check

# Final environment setup
export LC_ALL=en_US.UTF-8
export DKUBIN="$BINDIR"/dku
export PYTHONPATH="$DIP_HOME/lib/python:$DKUINSTALLDIR/python"

"$DKUPYTHONBIN" -m dataiku.apinode.admin "$@"