import os, os.path as osp
import json
import logging
from . import utils
from random import SystemRandom
import string

def generate_secure_random_string(N):
    cryptogen = SystemRandom()
    return ''.join(cryptogen.choice(string.ascii_uppercase + string.digits) for _ in range(N))

def get_or_create_api_key():

    auth_file_path = osp.join(os.getenv("DKU_LAMBDA_HOME"), "config", "adminkeys.json")

    keys = utils.json_loadf(auth_file_path)

    for key in keys.get("keys", []):
        if key.get("createdBy", None) == "cli-apinode-admin":
            return key["key"]

    logging.info("Creating an Admin key for CLI client")

    key = {
        "key" : generate_secure_random_string(32),
        "label" : "Key generated by CLI API client",
        "createdBy" : "cli-apinode-admin"
    }
    if not "keys" in keys:
        keys["keys"] = []
    keys["keys"].append(key)

    utils.json_dumpf(auth_file_path, keys)

    return key["key"]